### ISSUE TITLE
I have a question about this

### ISSUE THREAD

**Issue by jimbaethegreat** [yashrathi-git/vimeo_downloader#1]
Hi 

Thanks for release
Is there any way to download video with password?
(based on knowledge of password)

**Comment by yashrathi-git** [comment]
Currently, `vimeo-downloader` doesn't support downloading password-protected videos. I am unaware of any other tools that do support that. Please share a demo password-protected video URL with the password, so I could probably look into it.

**Comment by yashrathi-git** [comment]
Since I have no more information to help you or implement this feature. I am closing this issue.
