### ISSUE TITLE
Support for downloading private

### ISSUE THREAD

**Issue by bhanuunrivalled** [yashrathi-git/vimeo_downloader#2]
How do I download a Private video??

I have some videos uploaded by my team into my Vimeo account I want to download them using this class is it possible?

currently, I get  `raise URLNotSupported`

my url is like this

https://vimeo.com/groups/test29/videos/1234445552

**Comment by yashrathi-git** [comment]
I have updated vimeo-downloader to support public group videos. You could use it by downloading latest version of vimeo_downloader from github.
```sh
git clone https://github.com/yashrathi-git/vimeo_downloader
cd vimeo_downloader
pip install .
```
Or run this command
```sh
pip install git+https://github.com/yashrathi-git/vimeo_downloader
```

**Comment by bhanuunrivalled** [comment]
ok I see it in the code now I will check it and close this Thanks

**Comment by bhanuunrivalled** [comment]
HI @yashrathi-git ,

My URL is protected by login with Gmail. it gives 403 first and tries another way and get 404 do you know any workaround for this??

**Comment by yashrathi-git** [comment]
@bhanuunrivalled 
Now you could use cookies to download password-protected videos. 
## To get the cookies
While logged into your account, go to the video URL. Press Command + Shift + C or Control + Shift + C to get to developer tools. Go to network tab and reload the page. You would see all requests that were made. Click on the top one and scroll down to "Request Headers", there you would find cookie parameter, copy its value.

## Make sure you are on latest version
```py
pip install git+https://github.com/yashrathi-git/vimeo_downloader
```

## Example: 
```py
from vimeo_downloader import Vimeo

cookies = """ paste cookies here """

v = Vimeo(
    url="URL",
    cookies=cookies,
)
print("Name: ", v.metadata.title)
print("Description: ", v.metadata.description)

print(v.best_stream.direct_url)

## Download
print(v.best_stream.download())

```

**Comment by bhanuunrivalled** [comment]
Awesome thanks 🙏🏻

**Comment by 89z** [comment]
https://github.com/yashrathi-git/vimeo_downloader/issues/4
