### ISSUE TITLE
How insert referer on header?

### ISSUE THREAD

**Issue by blackexchange** [yashrathi-git/vimeo_downloader#20]
I need download https://player.vimeo.com/video/605813486
but i need pass to request referer website on header. "https://cursos.luiztools.com.br/"

**Comment by yashrathi-git** [comment]
https://github.com/yashrathi-git/vimeo_downloader#downloading-embed-only-videos

**Comment by blackexchange** [comment]
`from vimeo_downloader import Vimeo
cookies = """
    vuid=pl1266809688.1921417545; has_uploaded=1; player="volume=1"; _ga=GA1.2.799744625.1699639821; __cf_bm=Vacaqpk3jbvGe2mw8AYrp1eCOv34eOxsXPejJ2UXn3A-1700080558-0-AZ+gtKjqjl6s9lipm0PWDIqvrUA31biUBVg4BfWWimRH4bOMvWYhCOwcAME7gCjSowsPfajyMTHUf5m3nQ9HUJs=
 """.strip()

v = Vimeo('https://player.vimeo.com/video/597362348',
             embedded_on='https://cursos.luiztools.com.br/topico/07-criptografia-aes/', cookies=cookies)`

**Comment by blackexchange** [comment]
v.best_stream.download
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-17-2fe5041bf3dc>](https://localhost:8080/#) in <cell line: 1>()
----> 1 v.best_stream.download

[/usr/local/lib/python3.10/dist-packages/vimeo_downloader/__init__.py](https://localhost:8080/#) in best_stream(self)
    368     @property
    369     def best_stream(self) -> _Stream:
--> 370         return self.streams[-1]
    371 
    372     def __repr__(self):

IndexError: list index out of range
