### ISSUE TITLE
Unable to fetch the video.

### ISSUE THREAD

**Issue by rufia2000** [yashrathi-git/vimeo_downloader#5]
Hi, 
Thank you for this masterpiece . However I am getting this error: "Unable to fetch the video.". This occurs after trying to download an embedded video.
Can you help me?

**Comment by yashrathi-git** [comment]
Hi @rufia2000 
If you get this error, 
```py
RequestError: 403: Unable to fetch the video.
```
because of the way Vimeo, works you could sometimes see this error. For now, the best way to fix it would be to try downloading different quality of the particular video.
