### ISSUE TITLE
Stopped working for private urls?

### ISSUE THREAD

**Issue by vitsum** [yashrathi-git/vimeo_downloader#7]
Used to work couple of days ago.
when you have a link like 
https://vimeo.com/333333333/abcaa66177 [the link is wrong, just an example]
I used the part https://vimeo.com/333333333 and it worked.
and now it stopped working, it gives 403 error:
403: If the video is embed only, also provide the url on which it is embedded, Vimeo(url=<vimeo_url>,embedded_on=<url>)
tried to paste https://vimeo.com/333333333/abcaa66177 as embedded_on but the same result.
tried to use Vimeo.from_video_id but anyway I get the same 403 error.

**Comment by yashrathi-git** [comment]
403 status code means you don't have access to the video, so you might require to authenticate. Check out [this section](https://github.com/yashrathi-git/vimeo_downloader#downloading-videos-that-require-login) of README

**Comment by vitsum** [comment]
I can watch the video using the link https://vimeo.com/363026000/3c4aa66177

and downloading worked a couple of days ago but now it doesn't work for
some reason.

вт, 24 авг. 2021 г. в 21:42, Yash Rathi ***@***.***>:

**Comment by yashrathi-git** [comment]
> I can watch the video using the link https://vimeo.com/363026000/3c4aa66177

Hi @vitsum, I tried it this is working:
```py
>>> from vimeo_downloader import Vimeo
>>> v = Vimeo.from_video_id('363026000')
>>> s = v.best_stream
>>> s.title
'Вебинар ...'
>>> v.streams
[Stream(240p), Stream(360p), Stream(480p)]
```

**Comment by vitsum** [comment]
> > I can watch the video using the link https://vimeo.com/363026000/3c4aa66177
> 
> Hi @vitsum, I tried it this is working:
> 
> ```python
> >>> from vimeo_downloader import Vimeo
> >>> v = Vimeo.from_video_id('363026000')
> >>> s = v.best_stream
> >>> s.title
> 'Вебинар ...'
> >>> v.streams
> [Stream(240p), Stream(360p), Stream(480p)]
> ```

weird. tried exactly your code
![image](https://user-images.githubusercontent.com/3277059/130650357-9c8f44f7-1e37-4a9f-afb7-2e7450eec286.png)

**Comment by vitsum** [comment]
it's on repl.it so may be something wrong on their side. tried to reinstall the module and now I can't even install it back

**Comment by vitsum** [comment]
Created a new repl but still not working. But it worked earlier. So weird :( Thanks for your help.

**Comment by yashrathi-git** [comment]
Yes @vitsum, it's not working on replit. I think because either replit or Vimeo is blocking requests from that IP. Most probably Replit itself might be blocking requests.
